### ISSUE TITLE
Multiple issues in 1.19 version

### ISSUE THREAD

**Issue by RedBeast1959** [seymourimadeit/guardvillagers#85] opened 2022-06-12 06:59 UTC
Forge: 1.19-forge-41.0.17
mod: guardvillagers-1.19-1.5.0.jar, bigbrain-1.6.0.jar, 1.19 version of Serilum mods

1. in-game mod version is marked as 1.4.2, not 1.5.0
![javaw 2022-06-12 14-59-18-154](https://user-images.githubusercontent.com/100399264/173221180-8a4c7708-ba3d-45f0-bbb3-98e490a6292c.png)

2. Guard common sense option is on, but guard is not afraid of polar bear
Also guard health regeneration amount configuration is not working either.
![javaw 2022-06-12 14-59-06-295](https://user-images.githubusercontent.com/100399264/173221247-5913cf11-c265-4473-bc5e-101bc2068698.png)
![2022-06-12_14 59 36](https://user-images.githubusercontent.com/100399264/173221252-3a5a161f-cb9b-4d38-8a61-c1118669dad7.png)

3. Illager common sense option is on, but illager is not afraid of polar bear
![javaw 2022-06-12 15-00-27-733](https://user-images.githubusercontent.com/100399264/173221318-9c9ef244-dc73-4f7d-b7d8-52df0ec73b9f.png)
![javaw 2022-06-12 15-01-04-163](https://user-images.githubusercontent.com/100399264/173221322-076dc9eb-0b26-4271-a7b2-134d88993427.png)

**Comment by seymourimadeit** [comment] 2022-06-13 06:01
I can confirm that the version numbering and guards running away from polar bears are bugged but the illagers running away and guard regeneration amount seem to work for me. since you're using a config gui mod that updates the changes live could you try to load up your game again and see if those options work?

**Comment by seymourimadeit** [comment] 2022-07-08 05:08
Marking as closed for now.

**Closed as completed by seymourimadeit** 2022-07-08 05:08 UTC
