### ISSUE TITLE
Crash when rendering guard villagers

### ISSUE THREAD

**Issue by DarthCaesium** [seymourimadeit/guardvillagers#222] opened 2024-10-03 19:37 UTC
Hi! As the title suggests, when rendering a guard villager with my modded setup, the game crashes. For context, upon reloading, I am in a village. When I disabled Guard Villagers, my game did not crash. Someone else on your GitHub page apparently had the same issue but for the unofficial Fabric version, which got me thinking: I use Sinytra Connector, so maybe there is some issues with using Guard Villagers with it due to some kind of Fabric rendering that has issues with the mod?  

Anyway, here's the crash report: https://mclo.gs/Vc0VC5B

I hope you can help, and I hope that I can be helpful to you.

**Comment by seymourimadeit** [comment] 2024-10-04 00:45
From an initial look I think this looks to be more of an issue on Nyf's Quiver's side, could you report this bug to them and see if it can be fixed on their side (it looks like it could be reproduced with any crossbow using mob, not just guards) and if not I will reopen this issue

**Closed as completed by seymourimadeit** 2024-10-04 00:45 UTC
